version: '3.9'

services:

  postgresql-db:
    container_name: postgresdb
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - './project_data/:/docker-entrypoint-initdb.d/'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-cache:
    container_name: redis
    image: redis
    restart: always
    volumes:
      - cache:/data
    ports:
      - "6379:6379"

  backend:
    container_name: backend_application
    build: .
    depends_on:
      postgresql-db:
        condition: service_healthy
    ports:
      - "8050:8050"
    restart: on-failure
volumes:
  cache:
    driver: local
